# Generated by Django 5.1.7 on 2025-03-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
