# Generated by Django 5.1.7 on 2025-03-11 10:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pageblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='content',
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='text_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
